import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/Header";
import { Notes } from "~/components/Notes";
import { Content } from "~/components/Content";
import { Line } from "~/components/Line";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Notebook</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Notes />
        <Line />
        <Content />
      </main>
    </>
  );
};

export default Home;
